import JSZip from 'jszip';
import { GOOGLE_CLIENT_ID } from './config.js';
import { readWorkbook, detectColumn, prepareRows, summarizeUrl, makeProblemsCsv, zipName, extractDriveFileId, parseImageMime } from './parser.js';
import './style.css';

const app = document.querySelector('#app');
app.innerHTML = `<main class="shell"><header><div class="eyebrow">GS TOOLS · PRIVASI UTAMA</div><h1>Download Foto Drive by GS</h1><p class="subtitle">Download dan beri nama foto dari data Excel secara otomatis.</p><span class="security">● Diproses lokal di browser — data tidak diunggah.</span></header>
<section class="steps"><article class="card"><div class="step"><b>01</b><div><h2>Pilih data</h2><p>Masukkan file Excel atau CSV konsumen.</p></div></div><label class="drop" id="drop"><input id="file" type="file" accept=".xlsx,.xls,.csv" hidden><span class="drop-icon">＋</span><strong>Tarik file ke sini</strong><span>atau</span><button type="button" class="secondary" id="pick">Pilih Excel/CSV</button><small id="fileName">Belum ada file dipilih</small></label><label class="field" id="sheetWrap" hidden>Sheet<select id="sheet"></select></label></article>
<article class="card"><div class="step"><b>02</b><div><h2>Tentukan kolom</h2><p>Kolom terdeteksi otomatis dan dapat diubah.</p></div></div><div class="fields"><label class="field">Kolom nama file<select id="nameCol" disabled></select></label><label class="field">Kolom link foto<select id="linkCol" disabled></select></label><label class="field">Kolom nomor/ID <em>opsional</em><select id="idCol" disabled></select></label></div></article>
<article class="card"><div class="step"><b>03</b><div><h2>Format nama file</h2><p>Pastikan hasil rapi sebelum mulai.</p></div></div><div class="format"><label><input type="radio" name="mode" value="name" checked> <b>Nama</b><span> BUDI SANTOSO.jpg</span></label><label><input type="radio" name="mode" value="number"> <b>Nomor - Nama</b><span> 12 - BUDI SANTOSO.jpg</span></label><label><input type="radio" name="mode" value="id"> <b>ID - Nama</b><span> A102 - BUDI SANTOSO.jpg</span></label></div><label class="check"><input id="caps" type="checkbox"> Ubah nama menjadi HURUF KAPITAL</label></article>
<article class="card"><div class="step"><b>04</b><div><h2>Simpan hasil</h2><p>Foto tidak pernah menggantikan file yang sudah ada.</p></div></div><div class="actions"><button class="secondary" id="connect">Hubungkan Google Drive</button><button class="secondary" id="folder">Pilih Folder Hasil</button></div><label class="check"><input id="makeFoto" type="checkbox" checked> Buat folder FOTO di dalam folder yang dipilih</label><p class="hint" id="folderHint">Chrome/Edge akan meminta izin folder. Browser lain menggunakan ZIP.</p></article></section>
<section class="card preview-card"><div class="preview-head"><div><h2>Preview</h2><p id="summary">Pilih data untuk melihat ringkasan.</p></div><span class="status" id="driveStatus">Drive belum terhubung</span></div><div class="summary-grid" id="summaryGrid"></div><div class="table-wrap"><table><thead><tr><th>Baris</th><th>Nama</th><th>Nomor/ID</th><th>Link foto</th><th>Nama file hasil</th><th>Status validasi</th></tr></thead><tbody id="rows"><tr><td colspan="6" class="empty">Belum ada data.</td></tr></tbody></table></div><div class="progress-area" id="progressArea" hidden><div class="progress-label"><span id="progressText">Memproses…</span><button class="link-btn" id="cancel">Batalkan</button></div><progress id="progress" max="1" value="0"></progress></div><div class="bottom-actions"><button class="primary" id="download" disabled>Download Semua Foto</button><button class="secondary" id="retry" hidden>Coba Lagi yang Gagal</button><button class="secondary" id="problems" hidden>Download Daftar Masalah CSV</button><button class="secondary" id="newData" hidden>Proses Data Baru</button></div><div id="issues" class="issues" hidden></div></section><footer>Data Excel dan foto diproses langsung di browser ini dan tidak dikirim ke server.</footer></main>`;

const $ = (s) => document.querySelector(s); let data = null; let rows = []; let folderHandle = null; let token = null; let cancelled = false; let lastFile;
const supportedDirect = 'showDirectoryPicker' in window;
function fillSelect(el, headers, selected = -1, optional = false) { el.innerHTML = optional ? '<option value="-1">— Tidak digunakan —</option>' : ''; headers.forEach((h, i) => { const o = document.createElement('option'); o.value = i; o.textContent = `${i + 1}. ${h || `Kolom ${i + 1}`}`; o.selected = i === selected; el.append(o); }); el.disabled = false; }
function refresh() { if (!data) return; const options = { nameCol: +$('#nameCol').value, linkCol: +$('#linkCol').value, idCol: +$('#idCol').value, mode: document.querySelector('input[name=mode]:checked').value, uppercase: $('#caps').checked }; rows = prepareRows(data.sheets.find((s) => s.name === $('#sheet').value), options); render(); }
function render() { const counts = { total: rows.length, found: rows.filter((r) => r.url).length, emptyLink: rows.filter((r) => r.problem?.[0] === 'link-kosong').length, emptyName: rows.filter((r) => r.problem?.[0] === 'nama-kosong').length, duplicate: rows.length - new Set(rows.map((r) => r.name).filter(Boolean)).size, invalid: rows.filter((r) => r.problem?.[0] === 'link-tidak-valid' || r.problem?.[0] === 'folder').length }; $('#summary').textContent = `${counts.total} data siap diperiksa · ${counts.found} link ditemukan`; $('#summaryGrid').innerHTML = Object.entries({ 'Total data': counts.total, 'Link ditemukan': counts.found, 'Link kosong': counts.emptyLink, 'Nama kosong': counts.emptyName, 'Nama sama': counts.duplicate, 'Link bermasalah': counts.invalid }).map(([k, v]) => `<div><b>${v}</b><span>${k}</span></div>`).join(''); $('#rows').innerHTML = rows.slice(0, 10).map((r) => `<tr><td>${r.excelRow}</td><td>${esc(r.name || '—')}</td><td>${esc(r.id || '—')}</td><td title="${esc(r.url)}"><span class="url">${esc(summarizeUrl(r.url) || '—')}</span></td><td>${esc(r.filename)}</td><td>${r.problem ? `<span class="bad">${esc(r.problem[1])}</span>` : '<span class="good">Siap</span>'}</td></tr>`).join('') || '<tr><td colspan="6" class="empty">Belum ada data.</td></tr>'; const issues = rows.filter((r) => r.problem); $('#problems').hidden = !issues.length; $('#issues').hidden = !issues.length; $('#issues').innerHTML = issues.slice(0, 20).map((r) => `<div><b>Baris ${r.excelRow}</b> · ${esc(r.name || 'Tanpa nama')} — ${esc(r.problem[1])}</div>`).join(''); $('#download').disabled = !rows.length || +$('#nameCol').value < 0 || +$('#linkCol').value < 0; }
function esc(s) { return String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])); }
async function loadFile(file) { lastFile = file; $('#fileName').textContent = file.name; data = await readWorkbook(file); $('#sheetWrap').hidden = data.sheets.length < 2; $('#sheet').innerHTML = data.sheets.map((s) => `<option>${esc(s.name)}</option>`).join(''); const s = data.sheets[0]; fillSelect($('#nameCol'), s.headers, detectColumn(s.headers, ['nama', 'name', 'nama lengkap', 'nama siswa', 'nama karyawan', 'nama peserta'])); fillSelect($('#linkCol'), s.headers, detectColumn(s.headers, ['foto', 'link foto', 'photo', 'link drive', 'drive', 'pas foto', 'upload foto'])); fillSelect($('#idCol'), s.headers, detectColumn(s.headers, ['no', 'nomor', 'id', 'nis', 'nip', 'nik', 'nomor peserta']), true); refresh(); }
$('#pick').onclick = () => $('#file').click(); $('#file').onchange = (e) => loadFile(e.target.files[0]); $('#drop').ondragover = (e) => { e.preventDefault(); $('#drop').classList.add('drag'); }; $('#drop').ondragleave = () => $('#drop').classList.remove('drag'); $('#drop').ondrop = (e) => { e.preventDefault(); $('#drop').classList.remove('drag'); loadFile(e.dataTransfer.files[0]); }; $('#sheet').onchange = () => { const s = data.sheets.find((x) => x.name === $('#sheet').value); fillSelect($('#nameCol'), s.headers, detectColumn(s.headers, ['nama', 'name', 'nama lengkap', 'nama siswa', 'nama karyawan', 'nama peserta'])); fillSelect($('#linkCol'), s.headers, detectColumn(s.headers, ['foto', 'link foto', 'photo', 'link drive', 'drive', 'pas foto', 'upload foto'])); fillSelect($('#idCol'), s.headers, detectColumn(s.headers, ['no', 'nomor', 'id', 'nis', 'nip', 'nik', 'nomor peserta']), true); refresh(); }; ['nameCol', 'linkCol', 'idCol', 'caps'].forEach((id) => $(`#${id}`).onchange = refresh); document.querySelectorAll('input[name=mode]').forEach((e) => e.onchange = refresh);
$('#folder').onclick = async () => { if (!supportedDirect) { $('#folderHint').textContent = 'Browser ini akan memakai fallback ZIP.'; return; } folderHandle = await window.showDirectoryPicker({ mode: 'readwrite' }); $('#folderHint').textContent = `Folder dipilih: ${folderHandle.name}`; }; $('#connect').onclick = () => { if (!GOOGLE_CLIENT_ID) { $('#driveStatus').textContent = 'Tambahkan Client ID di src/config.js'; return; } if (!window.google?.accounts?.oauth2) { $('#driveStatus').textContent = 'SDK Google belum siap.'; return; } const client = google.accounts.oauth2.initTokenClient({ client_id: GOOGLE_CLIENT_ID, scope: 'https://www.googleapis.com/auth/drive.readonly', callback: (r) => { token = r.access_token; $('#driveStatus').textContent = 'Google Drive terhubung'; } }); client.requestAccessToken({ prompt: 'select_account' }); };
async function getImage(r) {
  const id = extractDriveFileId(r.url);
  let response;
  if (id) {
    if (!token) throw new Error('Hubungkan Google Drive terlebih dahulu untuk mengunduh link Google Drive.');
    const meta = await fetch('https://www.googleapis.com/drive/v3/files/' + id + '?fields=mimeType,capabilities,name', { headers: { Authorization: 'Bearer ' + token } });
    if (!meta.ok) throw new Error(meta.status === 401 || meta.status === 403 ? 'Akses ditolak atau sesi Google Drive berakhir.' : 'Metadata gagal (' + meta.status + ')');
    const info = await meta.json();
    if (info.mimeType === 'application/vnd.google-apps.folder') throw new Error('Link mengarah ke folder, bukan file foto.');
    if (info.capabilities && info.capabilities.canDownload === false) throw new Error('File tidak mengizinkan download.');
    if (!String(info.mimeType || '').startsWith('image/')) throw new Error('File bukan gambar.');
    response = await fetch('https://www.googleapis.com/drive/v3/files/' + id + '?alt=media', { headers: { Authorization: 'Bearer ' + token } });
  } else {
    response = await fetch(r.url, { mode: 'cors' });
  }
  if (!response.ok) throw new Error(response.status === 401 || response.status === 403 ? 'Akses ditolak atau sesi Google Drive berakhir.' : 'Download gagal (' + response.status + ')');
  const type = response.headers.get('content-type') || '';
  const blob = await response.blob();
  const ext = parseImageMime(type, await blob.arrayBuffer());
  if (!ext) throw new Error('File bukan gambar atau respons bukan gambar.');
  return { blob, name: r.filename.replace(/\.[^.]+$/, '.' + ext) };
}
async function process() { cancelled = false; $('#progressArea').hidden = false; $('#download').disabled = true; let ok = 0; let failed = 0; const failures = []; const queue = rows.filter((r) => !r.problem); const files = []; for (let i = 0; i < queue.length; i += 1) { if (cancelled) break; const r = queue[i]; $('#progressText').textContent = `Memproses ${i + 1} dari ${queue.length} · ${r.name}`; $('#progress').value = (i + 1) / queue.length; try { const result = await getImage(r); files.push(result); ok += 1; } catch (e) { failed += 1; failures.push({ ...r, type: 'download-gagal', message: e.message }); } } if (supportedDirect && folderHandle) { const target = $('#makeFoto').checked ? await folderHandle.getDirectoryHandle('FOTO', { create: true }) : folderHandle; for (const f of files) { const h = await target.getFileHandle(f.name, { create: true }); const w = await h.createWritable(); await w.write(f.blob); await w.close(); } } else { const zip = new JSZip(); files.forEach((f) => zip.file(f.name, f.blob)); const blob = await zip.generateAsync({ type: 'blob' }); const a = Object.assign(document.createElement('a'), { href: URL.createObjectURL(blob), download: zipName(lastFile?.name) }); a.click(); URL.revokeObjectURL(a.href); } $('#progressText').textContent = cancelled ? `Dibatalkan · Berhasil ${ok}` : `Selesai · Berhasil ${ok}, gagal ${failed}`; $('#download').disabled = false; $('#retry').hidden = !failures.length; $('#problems').hidden = !(failures.length || rows.some((r) => r.problem)); window.lastFailures = failures; }
$('#download').onclick = process; $('#cancel').onclick = () => { cancelled = true; }; $('#problems').onclick = () => { const bad = [...rows.filter((r) => r.problem).map((r) => ({ ...r, type: r.problem[0], message: r.problem[1] })), ...(window.lastFailures || [])]; const a = Object.assign(document.createElement('a'), { href: URL.createObjectURL(new Blob([makeProblemsCsv(bad)], { type: 'text/csv;charset=utf-8' })), download: 'daftar-masalah.csv' }); a.click(); }; $('#retry').onclick = process; $('#newData').onclick = () => location.reload();
